import sqlite3

from db import DB_PATH

def create_database():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT,
            price REAL,
            description TEXT,
            is_organic INTEGER DEFAULT 0
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER,
            rating REAL,
            reviewer_name TEXT,
            review_text TEXT,
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            product_name TEXT NOT NULL,
            price REAL NOT NULL,
            ordered_at TEXT NOT NULL DEFAULT (datetime('now')),
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    products = [
        # --- Honey (8) ---
        (1,  "Organic Raw Honey",             "honey",        14.99, "Pure organic raw honey, unfiltered and cold-pressed",                1),
        (2,  "Wildflower Honey",              "honey",        12.99, "Natural wildflower honey from local beekeepers",                     0),
        (3,  "Organic Manuka Honey",          "honey",        29.99, "Premium organic Manuka honey from New Zealand",                      1),
        (4,  "Clover Honey",                  "honey",         8.99, "Classic clover honey, smooth and sweet",                             0),
        (5,  "Organic Buckwheat Honey",       "honey",        18.99, "Dark and robust organic buckwheat honey, antioxidant-rich",          1),
        (6,  "Orange Blossom Honey",          "honey",        15.99, "Light and floral orange blossom honey",                              0),
        (7,  "Organic Acacia Honey",          "honey",        17.99, "Light and mild organic acacia honey, low glycemic index",            1),
        (8,  "Creamed Honey",                 "honey",        11.99, "Smooth creamed honey with spreadable texture",                       0),
        # --- Oils (4) ---
        (9,  "Organic Extra Virgin Olive Oil", "oil",         16.99, "Cold-pressed organic EVOO from Mediterranean olives",                1),
        (10, "Coconut Oil",                   "oil",          12.49, "Refined coconut oil, great for high-heat cooking",                   0),
        (11, "Organic Flaxseed Oil",          "oil",          14.99, "Cold-pressed organic flaxseed oil, rich in omega-3",                 1),
        (12, "Avocado Oil",                   "oil",          18.99, "Cold-pressed avocado oil, high smoke point",                         0),
        # --- Nuts & Seeds (4) ---
        (13, "Organic Almonds",               "nuts",         11.99, "Raw organic almonds, unsalted, non-GMO certified",                   1),
        (14, "Roasted Cashews",               "nuts",          9.99, "Lightly salted dry-roasted cashews",                                 0),
        (15, "Organic Chia Seeds",            "seeds",         8.49, "Organic black chia seeds, high in fiber and omega-3",                1),
        (16, "Mixed Nuts",                    "nuts",         13.99, "Premium mix of walnuts, pecans, almonds and Brazil nuts",            0),
        # --- Grains & Cereals (4) ---
        (17, "Organic Quinoa",                "grains",       10.99, "Organic white quinoa, complete protein, gluten-free",                1),
        (18, "Rolled Oats",                   "grains",        5.49, "Whole grain rolled oats, great for porridge and baking",             0),
        (19, "Organic Brown Rice",            "grains",        7.99, "Long-grain organic brown rice, naturally gluten-free",               1),
        (20, "Steel-Cut Oats",                "grains",        6.99, "Traditional steel-cut oats, low GI, hearty texture",                 0),
        # --- Tea & Coffee (4) ---
        (21, "Organic Green Tea",             "tea",          12.99, "Japanese organic sencha green tea, 50 bags",                         1),
        (22, "Chamomile Tea",                 "tea",           8.99, "Dried chamomile flowers, caffeine-free, soothing",                   0),
        (23, "Organic Ethiopian Coffee",      "coffee",       16.99, "Single-origin organic Arabica, medium roast whole bean",             1),
        (24, "Dark Roast Espresso Blend",     "coffee",       14.49, "Bold dark roast espresso blend, ground",                             0),
        # --- Snacks (4) ---
        (25, "Organic Granola",               "snacks",        9.99, "Organic oat granola with honey, almonds and dried cranberries",      1),
        (26, "Rice Cakes",                    "snacks",        4.49, "Lightly salted brown rice cakes, low calorie",                       0),
        (27, "Organic Dried Mango",           "snacks",        7.99, "Unsweetened organic dried mango slices, no preservatives",           1),
        (28, "Trail Mix",                     "snacks",        8.49, "Classic trail mix with raisins, M&Ms, peanuts and sunflower seeds",  0),
        # --- Dairy Alternatives (4) ---
        (29, "Organic Almond Milk",           "dairy-alt",     4.99, "Unsweetened organic almond milk, fortified with calcium",            1),
        (30, "Oat Milk",                      "dairy-alt",     4.49, "Barista-style oat milk, great for coffee",                           0),
        (31, "Organic Coconut Milk",          "dairy-alt",     3.99, "Full-fat organic coconut milk, great for curries",                   1),
        (32, "Soy Milk",                      "dairy-alt",     3.49, "Unsweetened soy milk, high protein",                                 0),
        # --- Superfoods (8) ---
        (33, "Organic Spirulina Powder",      "superfoods",    19.99, "Nutrient-dense blue-green algae powder for smoothies",               1),
        (34, "Cacao Nibs",                    "superfoods",    11.49, "Crunchy cacao nibs with a rich chocolate flavor",                     0),
        (35, "Organic Maca Powder",           "superfoods",    14.99, "Earthy maca root powder for energy-focused drinks",                   1),
        (36, "Hemp Hearts",                   "superfoods",    12.99, "Soft shelled hemp seeds with a mild nutty taste",                     0),
        (37, "Goji Berries",                  "superfoods",    10.99, "Dried goji berries, sweet and tangy superfruit snack",                0),
        (38, "Organic Matcha Powder",         "superfoods",    18.49, "Ceremonial-grade organic matcha for lattes and baking",               1),
        (39, "Pumpkin Seeds",                 "superfoods",     9.49, "Roasted pumpkin seeds packed with crunch and minerals",               0),
        (40, "Acai Powder",                   "superfoods",    17.99, "Freeze-dried acai powder for bowls and smoothies",                   0),
        # --- Pasta (8) ---
        (41, "Organic Spaghetti",             "pasta",          3.99, "Durum wheat spaghetti made with organic semolina",                    1),
        (42, "Penne Rigate",                  "pasta",          2.99, "Classic ridged penne pasta for hearty sauces",                        0),
        (43, "Chickpea Pasta",                "pasta",          4.99, "Protein-rich chickpea pasta, gluten-free",                            1),
        (44, "Brown Rice Pasta",              "pasta",          4.49, "Tender brown rice pasta with a mild flavor",                          0),
        (45, "Organic Fusilli",               "pasta",          3.79, "Organic spiral pasta that holds sauce beautifully",                  1),
        (46, "Lasagna Sheets",                "pasta",          4.29, "Flat lasagna sheets ready for layered bakes",                         0),
        (47, "Gluten-Free Lentil Pasta",      "pasta",          5.49, "Red lentil pasta with a hearty, satisfying texture",                  1),
        (48, "Whole Wheat Macaroni",          "pasta",          3.49, "Whole wheat macaroni for everyday comfort meals",                     0),
        # --- Sauces (8) ---
        (49, "Organic Marinara Sauce",        "sauces",         5.99, "Slow-simmered organic tomato sauce with basil and garlic",            1),
        (50, "Alfredo Sauce",                 "sauces",         6.49, "Creamy parmesan-style sauce for pasta and vegetables",                0),
        (51, "Organic Peanut Sauce",          "sauces",         4.99, "Savory organic peanut sauce for noodles and stir-fries",              1),
        (52, "Teriyaki Glaze",                "sauces",         5.49, "Sweet and salty glaze for bowls, tofu, and grilled meat",             0),
        (53, "Tomato Basil Pasta Sauce",      "sauces",         5.79, "Bright tomato sauce with fresh basil notes",                          0),
        (54, "Salsa Verde",                   "sauces",         4.79, "Tangy green salsa with tomatillo and cilantro",                       0),
        (55, "Organic Tahini Sauce",          "sauces",         6.99, "Creamy organic sesame sauce with lemon and garlic",                   1),
        (56, "Hot Sauce",                     "sauces",         3.99, "Spicy chili pepper sauce for everyday heat",                          0),
        # --- Spices (8) ---
        (57, "Organic Turmeric Powder",       "spices",         7.49, "Golden organic turmeric with warm earthy notes",                      1),
        (58, "Ground Cinnamon",               "spices",         4.99, "Sweet aromatic cinnamon for baking and drinks",                       0),
        (59, "Cumin Seeds",                   "spices",         3.99, "Toasty cumin seeds with a deep savory aroma",                         0),
        (60, "Smoked Paprika",                "spices",         5.49, "Rich smoked paprika with a warm peppery finish",                      0),
        (61, "Organic Black Pepper",          "spices",         6.49, "Freshly ground organic black pepper with bold aroma",                1),
        (62, "Garlic Powder",                 "spices",         4.49, "Convenient garlic powder for seasoning blends",                       0),
        (63, "Chili Flakes",                  "spices",         3.49, "Crushed red chili flakes for a quick heat boost",                     0),
        (64, "Cardamom Pods",                 "spices",         8.99, "Fragrant cardamom pods for tea, coffee, and desserts",                0),
        # --- Baking (8) ---
        (65, "Almond Flour",                  "baking",         9.99, "Finely ground almond flour for gluten-free baking",                   0),
        (66, "Organic Coconut Sugar",         "baking",         6.99, "Low-refined coconut sugar with caramel notes",                        1),
        (67, "Baking Soda",                   "baking",         2.49, "Kitchen staple for leavening and cleaning",                           0),
        (68, "Vanilla Extract",               "baking",         8.49, "Pure vanilla extract for cookies, cakes, and custards",              0),
        (69, "Organic Cocoa Powder",          "baking",         7.99, "Unsweetened organic cocoa powder with deep chocolate flavor",         1),
        (70, "Baking Powder",                 "baking",         2.29, "Double-acting baking powder for cakes and muffins",                   0),
        (71, "Tapioca Starch",                "baking",         4.29, "Smooth thickener for sauces and gluten-free baking",                  0),
        (72, "Brown Sugar",                   "baking",         3.99, "Soft brown sugar for baking and sweet sauces",                        0),
        # --- Canned (8) ---
        (73, "Organic Black Beans",           "canned",         2.49, "Tender organic black beans ready for quick meals",                    1),
        (74, "Chickpeas",                     "canned",         2.29, "Pantry-friendly chickpeas for salads and hummus",                     0),
        (75, "Diced Tomatoes",                "canned",         1.99, "Kitchen-ready diced tomatoes for soups and sauces",                   0),
        (76, "Coconut Cream",                 "canned",         3.49, "Rich coconut cream for curries and desserts",                         0),
        (77, "Organic Lentils",               "canned",         2.79, "Organic lentils in a convenient ready-to-use can",                    1),
        (78, "Sweet Corn",                    "canned",         1.79, "Sweet whole kernel corn for sides and casseroles",                    0),
        (79, "Kidney Beans",                  "canned",         2.19, "Hearty kidney beans for chili and stews",                             0),
        (80, "Pumpkin Puree",                 "canned",         3.29, "Smooth pumpkin puree for pies, soups, and baking",                    0),
        # --- Beverages (8) ---
        (81, "Sparkling Water",               "beverages",      1.49, "Lightly carbonated water with a crisp finish",                        0),
        (82, "Cold Brew Coffee",              "beverages",      4.99, "Smooth cold brew coffee concentrate, ready to pour",                  0),
        (83, "Kombucha",                      "beverages",      3.99, "Fermented tea beverage with a tangy probiotic profile",              0),
        (84, "Aloe Vera Drink",               "beverages",      2.99, "Refreshing aloe drink with a lightly sweet taste",                    0),
        (85, "Coconut Water",                 "beverages",      2.49, "Naturally hydrating coconut water with electrolytes",                 0),
        (86, "Herbal Tonic",                  "beverages",      3.49, "Botanical tonic with ginger and citrus notes",                        0),
        (87, "Oat Latte",                     "beverages",      4.49, "Creamy oat-based latte for a smooth coffee break",                    0),
        (88, "Green Juice",                   "beverages",      5.99, "Fresh pressed green juice with cucumber and apple",                   0),
        # --- Personal Care (8) ---
        (89, "Organic Shampoo",               "personal-care",   8.99, "Gentle organic shampoo with botanical extracts",                      1),
        (90, "Toothpaste",                    "personal-care",   4.99, "Mint toothpaste for daily oral care",                                 0),
        (91, "Body Wash",                     "personal-care",   7.49, "Refreshing body wash with a clean citrus scent",                     0),
        (92, "Deodorant",                     "personal-care",   6.49, "Long-lasting deodorant with a fresh scent",                           0),
        (93, "Face Cleanser",                 "personal-care",   9.49, "Daily facial cleanser for a gentle deep clean",                       0),
        (94, "Hand Soap",                     "personal-care",   4.49, "Foaming hand soap with a mild lavender scent",                        0),
        (95, "Lip Balm",                      "personal-care",   3.29, "Moisturizing lip balm for everyday use",                              0),
        (96, "Sunscreen",                     "personal-care",  12.99, "Broad-spectrum sunscreen with lightweight feel",                      0),
        # --- Household (4) ---
        (97, "Dish Soap",                     "household",       3.99, "Grease-cutting dish soap with fresh scent",                            0),
        (98, "Laundry Detergent",             "household",      14.99, "High-efficiency laundry detergent for everyday loads",               0),
        (99, "Paper Towels",                  "household",       7.99, "Strong absorbent paper towels for kitchen cleanup",                   0),
        (100, "Reusable Storage Bags",        "household",       9.99, "Reusable food storage bags for pantry and freezer use",               0),
    ]
    cursor.executemany("INSERT OR REPLACE INTO products VALUES (?, ?, ?, ?, ?, ?)", products)

    # Avg ratings (for reference):
    # Honey:      1→4.625✓  2→3.833  3→4.833($$)  4→3.5  5→4.625✓  6→4.167  7→4.75✓  8→4.0
    # Oils:       9→4.67   10→3.67  11→4.5        12→4.33
    # Nuts/Seeds: 13→4.75  14→4.0   15→4.5        16→3.75
    # Grains:     17→4.67  18→4.33  19→4.5        20→3.83
    # Tea/Coffee: 21→4.67  22→4.17  23→4.75       24→4.0
    # Snacks:     25→4.5   26→3.83  27→4.67       28→3.67
    # Dairy-alt:  29→4.5   30→4.33  31→4.5        32→3.67
    reviews = [
        # Honey
        (1, 5.0, "Alice",   "Amazing honey! Best I've ever tried."),
        (1, 4.0, "Bob",     "Good quality, will buy again."),
        (1, 5.0, "Carol",   "Excellent raw flavor, very pure."),
        (1, 4.5, "Dave",    "Very good, love that it's unfiltered."),
        (2, 4.0, "Eve",     "Decent honey for the price."),
        (2, 3.5, "Frank",   "Average, nothing special."),
        (2, 4.0, "Grace",   "Good everyday honey."),
        (3, 5.0, "Henry",   "Worth every penny, incredible quality."),
        (3, 4.5, "Iris",    "Excellent antibacterial properties."),
        (3, 5.0, "Jack",    "Best honey I have ever tasted."),
        (4, 3.5, "Kate",    "Okay for cooking, nothing fancy."),
        (4, 3.5, "Leo",     "Nothing special, pretty generic."),
        (4, 3.5, "Mia",     "Average clover honey."),
        (5, 5.0, "Noah",    "Rich bold flavor, great in tea."),
        (5, 4.0, "Olivia",  "Good strong honey, unique taste."),
        (5, 5.0, "Paul",    "Love the dark color and depth."),
        (5, 4.5, "Quinn",   "Great organic option at this price."),
        (6, 4.0, "Rachel",  "Nice floral flavor."),
        (6, 4.5, "Sam",     "Lovely and delicate."),
        (6, 4.0, "Tina",    "Good for baking."),
        (7, 5.0, "Uma",     "Perfect mild flavor, love it!"),
        (7, 4.5, "Victor",  "Excellent light honey."),
        (7, 4.5, "Wendy",   "Great product, very pure taste."),
        (7, 5.0, "Xavier",  "Wonderful, highly recommend."),
        (8, 4.0, "Yvonne",  "Nice spreadable texture."),
        (8, 4.0, "Zack",    "Good on toast."),
        (8, 4.0, "Amy",     "Decent creamed honey."),
        # Oils
        (9,  5.0, "Brian",  "Best olive oil I've used, very fresh."),
        (9,  4.5, "Clara",  "Great flavor, organic certified."),
        (9,  4.5, "Derek",  "Excellent quality, love it."),
        (10, 4.0, "Elena",  "Good for frying, neutral taste."),
        (10, 3.5, "Felix",  "Does the job, nothing exciting."),
        (10, 3.5, "Gina",   "Decent but slightly greasy."),
        (11, 5.0, "Harry",  "Great for smoothies, very fresh."),
        (11, 4.0, "Isla",   "Good omega-3 source, mild flavor."),
        (11, 4.5, "James",  "Love this for salad dressings."),
        (12, 4.5, "Karen",  "Excellent smoke point, tastes great."),
        (12, 4.0, "Liam",   "Good all-purpose oil."),
        (12, 4.5, "Maya",   "Great for cooking and salads."),
        # Nuts & Seeds
        (13, 5.0, "Nate",   "Crunchy and fresh, great snack."),
        (13, 4.5, "Olivia", "Love that they're organic and raw."),
        (13, 4.5, "Peter",  "Perfect size, very fresh."),
        (13, 5.0, "Rita",   "Best almonds I've bought online."),
        (14, 4.0, "Steve",  "Good cashews, nice crunch."),
        (14, 4.0, "Tara",   "Tasty but slightly over-salted."),
        (14, 4.0, "Ursula", "Good value for the quantity."),
        (15, 4.5, "Vince",  "Easy to add to smoothies, love it."),
        (15, 4.5, "Wanda",  "Great fiber source, very fresh."),
        (15, 4.5, "Xena",   "Good quality organic chia seeds."),
        (16, 4.0, "Yuri",   "Good mix, well-balanced variety."),
        (16, 3.5, "Zara",   "A bit too many peanuts for my taste."),
        (16, 4.0, "Alex",   "Nice mix for snacking."),
        (16, 3.5, "Blake",  "Would prefer fewer raisins."),
        # Grains
        (17, 5.0, "Chloe",  "Cooks perfectly, great nutty flavor."),
        (17, 4.5, "Dylan",  "Excellent protein content, love it."),
        (17, 4.5, "Ella",   "Best quinoa I've tried."),
        (18, 4.5, "Finn",   "Great oats, cook quickly and evenly."),
        (18, 4.0, "Gabi",   "Good quality, nice texture."),
        (18, 4.5, "Hugo",   "Reliable everyday oats."),
        (19, 4.5, "Irene",  "Nice chewy texture, great organic choice."),
        (19, 4.5, "Jake",   "Good quality, cooks evenly."),
        (19, 4.5, "Kara",   "Love the organic certification."),
        (20, 4.0, "Lars",   "Great texture, a bit longer to cook."),
        (20, 3.5, "Mona",   "Takes forever to cook but tastes good."),
        (20, 4.0, "Ned",    "Hearty and filling."),
        # Tea & Coffee
        (21, 5.0, "Opal",   "Delicate flavor, very smooth."),
        (21, 4.5, "Phil",   "Best green tea I've had, very fresh."),
        (21, 4.5, "Quinn",  "Great quality, calming and tasty."),
        (22, 4.0, "Rose",   "Very soothing before bed."),
        (22, 4.5, "Seth",   "Lovely floral notes, very relaxing."),
        (22, 4.0, "Tess",   "Good chamomile, nice and mild."),
        (23, 5.0, "Uri",    "Best coffee I've ever brewed at home."),
        (23, 4.5, "Vera",   "Amazing single-origin flavor."),
        (23, 4.5, "Will",   "Very smooth with great aroma."),
        (23, 5.0, "Xara",   "Exceptional quality, worth every penny."),
        (24, 4.0, "Yael",   "Strong and bold, perfect espresso."),
        (24, 4.0, "Zion",   "Good dark roast, consistent grind."),
        (24, 4.0, "Abe",    "Solid everyday espresso blend."),
        # Snacks
        (25, 4.5, "Beth",   "Delicious and not too sweet."),
        (25, 4.5, "Cole",   "Great texture, love the almonds."),
        (25, 4.5, "Dana",   "My go-to breakfast granola."),
        (26, 4.0, "Earl",   "Light and crispy, good for dieting."),
        (26, 3.5, "Faye",   "A bit bland but does the job."),
        (26, 4.0, "Glen",   "Good value, decent snack."),
        (27, 5.0, "Hope",   "So sweet and chewy, love these!"),
        (27, 4.5, "Ivan",   "Great that there's no added sugar."),
        (27, 4.5, "Jade",   "Perfect snack, very natural taste."),
        (28, 4.0, "Kent",   "Good mix, great for hiking."),
        (28, 3.5, "Luna",   "Too many M&Ms, prefer less candy."),
        (28, 3.5, "Marc",   "Decent but not my favorite mix."),
        # Dairy Alternatives
        (29, 4.5, "Nina",   "Great in coffee, smooth texture."),
        (29, 4.5, "Omar",   "Love the organic certification."),
        (29, 4.5, "Pam",    "Tastes great and not too thin."),
        (30, 4.5, "Rex",    "Perfect for lattes, froths well."),
        (30, 4.0, "Sara",   "Good oat milk, slightly sweet."),
        (30, 4.5, "Tom",    "Best barista oat milk I've tried."),
        (31, 4.5, "Una",    "Creamy and rich, great for curries."),
        (31, 4.5, "Vito",   "Full fat and delicious."),
        (31, 4.5, "Wren",   "Perfect coconut milk, great quality."),
        (32, 4.0, "Xio",    "Good protein content, mild flavor."),
        (32, 3.5, "Yosef",  "Slightly thin but good for cereal."),
        (32, 3.5, "Zola",   "Decent soy milk, nothing special."),
        # Superfoods
        (33, 4.5, "Ava1", "Organic Spirulina Powder has great quality and arrived fresh."),
        (33, 4.0, "Hugo2", "Solid value for a superfoods item; I would buy it again."),
        (33, 4.5, "Owen3", "I like using Organic Spirulina Powder in my regular routine."),
        (34, 4.5, "Ben1", "Cacao Nibs has great quality and arrived fresh."),
        (34, 4.0, "Ivy2", "Solid value for a superfoods item; I would buy it again."),
        (34, 4.5, "Pia3", "I like using Cacao Nibs in my regular routine."),
        (35, 4.5, "Cora1", "Organic Maca Powder has great quality and arrived fresh."),
        (35, 4.0, "Jonah2", "Solid value for a superfoods item; I would buy it again."),
        (35, 4.5, "Quinn3", "I like using Organic Maca Powder in my regular routine."),
        (36, 4.5, "Diego1", "Hemp Hearts has great quality and arrived fresh."),
        (36, 4.0, "Kira2", "Solid value for a superfoods item; I would buy it again."),
        (36, 4.5, "Rosa3", "I like using Hemp Hearts in my regular routine."),
        (37, 4.5, "Emma1", "Goji Berries has great quality and arrived fresh."),
        (37, 4.0, "Leo2", "Solid value for a superfoods item; I would buy it again."),
        (37, 4.5, "Sage3", "I like using Goji Berries in my regular routine."),
        (38, 4.5, "Finn1", "Organic Matcha Powder has great quality and arrived fresh."),
        (38, 4.0, "Mila2", "Solid value for a superfoods item; I would buy it again."),
        (38, 4.5, "Theo3", "I like using Organic Matcha Powder in my regular routine."),
        (39, 4.5, "Gia1", "Pumpkin Seeds has great quality and arrived fresh."),
        (39, 4.0, "Noah2", "Solid value for a superfoods item; I would buy it again."),
        (39, 4.5, "Uma3", "I like using Pumpkin Seeds in my regular routine."),
        (40, 4.5, "Hugo1", "Acai Powder has great quality and arrived fresh."),
        (40, 4.0, "Owen2", "Solid value for a superfoods item; I would buy it again."),
        (40, 4.5, "Vera3", "I like using Acai Powder in my regular routine."),
        # Pasta
        (41, 4.5, "Ivy1", "Organic Spaghetti has great quality and arrived fresh."),
        (41, 4.0, "Pia2", "Solid value for a pasta item; I would buy it again."),
        (41, 4.5, "Wes3", "I like using Organic Spaghetti in my regular routine."),
        (42, 4.5, "Jonah1", "Penne Rigate has great quality and arrived fresh."),
        (42, 4.0, "Quinn2", "Solid value for a pasta item; I would buy it again."),
        (42, 4.5, "Xena3", "I like using Penne Rigate in my regular routine."),
        (43, 4.5, "Kira1", "Chickpea Pasta has great quality and arrived fresh."),
        (43, 4.0, "Rosa2", "Solid value for a pasta item; I would buy it again."),
        (43, 4.5, "Yara3", "I like using Chickpea Pasta in my regular routine."),
        (44, 4.5, "Leo1", "Brown Rice Pasta has great quality and arrived fresh."),
        (44, 4.0, "Sage2", "Solid value for a pasta item; I would buy it again."),
        (44, 4.5, "Zane3", "I like using Brown Rice Pasta in my regular routine."),
        (45, 4.5, "Mila1", "Organic Fusilli has great quality and arrived fresh."),
        (45, 4.0, "Theo2", "Solid value for a pasta item; I would buy it again."),
        (45, 4.5, "Ava3", "I like using Organic Fusilli in my regular routine."),
        (46, 4.5, "Noah1", "Lasagna Sheets has great quality and arrived fresh."),
        (46, 4.0, "Uma2", "Solid value for a pasta item; I would buy it again."),
        (46, 4.5, "Ben3", "I like using Lasagna Sheets in my regular routine."),
        (47, 4.5, "Owen1", "Gluten-Free Lentil Pasta has great quality and arrived fresh."),
        (47, 4.0, "Vera2", "Solid value for a pasta item; I would buy it again."),
        (47, 4.5, "Cora3", "I like using Gluten-Free Lentil Pasta in my regular routine."),
        (48, 4.5, "Pia1", "Whole Wheat Macaroni has great quality and arrived fresh."),
        (48, 4.0, "Wes2", "Solid value for a pasta item; I would buy it again."),
        (48, 4.5, "Diego3", "I like using Whole Wheat Macaroni in my regular routine."),
        # Sauces
        (49, 4.5, "Quinn1", "Organic Marinara Sauce has great quality and arrived fresh."),
        (49, 4.0, "Xena2", "Solid value for a sauces item; I would buy it again."),
        (49, 4.5, "Emma3", "I like using Organic Marinara Sauce in my regular routine."),
        (50, 4.5, "Rosa1", "Alfredo Sauce has great quality and arrived fresh."),
        (50, 4.0, "Yara2", "Solid value for a sauces item; I would buy it again."),
        (50, 4.5, "Finn3", "I like using Alfredo Sauce in my regular routine."),
        (51, 4.5, "Sage1", "Organic Peanut Sauce has great quality and arrived fresh."),
        (51, 4.0, "Zane2", "Solid value for a sauces item; I would buy it again."),
        (51, 4.5, "Gia3", "I like using Organic Peanut Sauce in my regular routine."),
        (52, 4.5, "Theo1", "Teriyaki Glaze has great quality and arrived fresh."),
        (52, 4.0, "Ava2", "Solid value for a sauces item; I would buy it again."),
        (52, 4.5, "Hugo3", "I like using Teriyaki Glaze in my regular routine."),
        (53, 4.5, "Uma1", "Tomato Basil Pasta Sauce has great quality and arrived fresh."),
        (53, 4.0, "Ben2", "Solid value for a sauces item; I would buy it again."),
        (53, 4.5, "Ivy3", "I like using Tomato Basil Pasta Sauce in my regular routine."),
        (54, 4.5, "Vera1", "Salsa Verde has great quality and arrived fresh."),
        (54, 4.0, "Cora2", "Solid value for a sauces item; I would buy it again."),
        (54, 4.5, "Jonah3", "I like using Salsa Verde in my regular routine."),
        (55, 4.5, "Wes1", "Organic Tahini Sauce has great quality and arrived fresh."),
        (55, 4.0, "Diego2", "Solid value for a sauces item; I would buy it again."),
        (55, 4.5, "Kira3", "I like using Organic Tahini Sauce in my regular routine."),
        (56, 4.5, "Xena1", "Hot Sauce has great quality and arrived fresh."),
        (56, 4.0, "Emma2", "Solid value for a sauces item; I would buy it again."),
        (56, 4.5, "Leo3", "I like using Hot Sauce in my regular routine."),
        # Spices
        (57, 4.5, "Yara1", "Organic Turmeric Powder has great quality and arrived fresh."),
        (57, 4.0, "Finn2", "Solid value for a spices item; I would buy it again."),
        (57, 4.5, "Mila3", "I like using Organic Turmeric Powder in my regular routine."),
        (58, 4.5, "Zane1", "Ground Cinnamon has great quality and arrived fresh."),
        (58, 4.0, "Gia2", "Solid value for a spices item; I would buy it again."),
        (58, 4.5, "Noah3", "I like using Ground Cinnamon in my regular routine."),
        (59, 4.5, "Ava1", "Cumin Seeds has great quality and arrived fresh."),
        (59, 4.0, "Hugo2", "Solid value for a spices item; I would buy it again."),
        (59, 4.5, "Owen3", "I like using Cumin Seeds in my regular routine."),
        (60, 4.5, "Ben1", "Smoked Paprika has great quality and arrived fresh."),
        (60, 4.0, "Ivy2", "Solid value for a spices item; I would buy it again."),
        (60, 4.5, "Pia3", "I like using Smoked Paprika in my regular routine."),
        (61, 4.5, "Cora1", "Organic Black Pepper has great quality and arrived fresh."),
        (61, 4.0, "Jonah2", "Solid value for a spices item; I would buy it again."),
        (61, 4.5, "Quinn3", "I like using Organic Black Pepper in my regular routine."),
        (62, 4.5, "Diego1", "Garlic Powder has great quality and arrived fresh."),
        (62, 4.0, "Kira2", "Solid value for a spices item; I would buy it again."),
        (62, 4.5, "Rosa3", "I like using Garlic Powder in my regular routine."),
        (63, 4.5, "Emma1", "Chili Flakes has great quality and arrived fresh."),
        (63, 4.0, "Leo2", "Solid value for a spices item; I would buy it again."),
        (63, 4.5, "Sage3", "I like using Chili Flakes in my regular routine."),
        (64, 4.5, "Finn1", "Cardamom Pods has great quality and arrived fresh."),
        (64, 4.0, "Mila2", "Solid value for a spices item; I would buy it again."),
        (64, 4.5, "Theo3", "I like using Cardamom Pods in my regular routine."),
        (65, 4.5, "Gia1", "Almond Flour has great quality and arrived fresh."),
        (65, 4.0, "Noah2", "Solid value for a baking item; I would buy it again."),
        (65, 4.5, "Uma3", "I like using Almond Flour in my regular routine."),
        (66, 4.5, "Hugo1", "Organic Coconut Sugar has great quality and arrived fresh."),
        (66, 4.0, "Owen2", "Solid value for a baking item; I would buy it again."),
        (66, 4.5, "Vera3", "I like using Organic Coconut Sugar in my regular routine."),
        (67, 4.5, "Ivy1", "Baking Soda has great quality and arrived fresh."),
        (67, 4.0, "Pia2", "Solid value for a baking item; I would buy it again."),
        (67, 4.5, "Wes3", "I like using Baking Soda in my regular routine."),
        (68, 4.5, "Jonah1", "Vanilla Extract has great quality and arrived fresh."),
        (68, 4.0, "Quinn2", "Solid value for a baking item; I would buy it again."),
        (68, 4.5, "Xena3", "I like using Vanilla Extract in my regular routine."),
        (69, 4.5, "Kira1", "Organic Cocoa Powder has great quality and arrived fresh."),
        (69, 4.0, "Rosa2", "Solid value for a baking item; I would buy it again."),
        (69, 4.5, "Yara3", "I like using Organic Cocoa Powder in my regular routine."),
        (70, 4.5, "Leo1", "Baking Powder has great quality and arrived fresh."),
        (70, 4.0, "Sage2", "Solid value for a baking item; I would buy it again."),
        (70, 4.5, "Zane3", "I like using Baking Powder in my regular routine."),
        (71, 4.5, "Mila1", "Tapioca Starch has great quality and arrived fresh."),
        (71, 4.0, "Theo2", "Solid value for a baking item; I would buy it again."),
        (71, 4.5, "Ava3", "I like using Tapioca Starch in my regular routine."),
        (72, 4.5, "Noah1", "Brown Sugar has great quality and arrived fresh."),
        (72, 4.0, "Uma2", "Solid value for a baking item; I would buy it again."),
        (72, 4.5, "Ben3", "I like using Brown Sugar in my regular routine."),
        # Canned
        (73, 4.5, "Owen1", "Organic Black Beans has great quality and arrived fresh."),
        (73, 4.0, "Vera2", "Solid value for a canned item; I would buy it again."),
        (73, 4.5, "Cora3", "I like using Organic Black Beans in my regular routine."),
        (74, 4.5, "Pia1", "Chickpeas has great quality and arrived fresh."),
        (74, 4.0, "Wes2", "Solid value for a canned item; I would buy it again."),
        (74, 4.5, "Diego3", "I like using Chickpeas in my regular routine."),
        (75, 4.5, "Quinn1", "Diced Tomatoes has great quality and arrived fresh."),
        (75, 4.0, "Xena2", "Solid value for a canned item; I would buy it again."),
        (75, 4.5, "Emma3", "I like using Diced Tomatoes in my regular routine."),
        (76, 4.5, "Rosa1", "Coconut Cream has great quality and arrived fresh."),
        (76, 4.0, "Yara2", "Solid value for a canned item; I would buy it again."),
        (76, 4.5, "Finn3", "I like using Coconut Cream in my regular routine."),
        (77, 4.5, "Sage1", "Organic Lentils has great quality and arrived fresh."),
        (77, 4.0, "Zane2", "Solid value for a canned item; I would buy it again."),
        (77, 4.5, "Gia3", "I like using Organic Lentils in my regular routine."),
        (78, 4.5, "Theo1", "Sweet Corn has great quality and arrived fresh."),
        (78, 4.0, "Ava2", "Solid value for a canned item; I would buy it again."),
        (78, 4.5, "Hugo3", "I like using Sweet Corn in my regular routine."),
        (79, 4.5, "Uma1", "Kidney Beans has great quality and arrived fresh."),
        (79, 4.0, "Ben2", "Solid value for a canned item; I would buy it again."),
        (79, 4.5, "Ivy3", "I like using Kidney Beans in my regular routine."),
        (80, 4.5, "Vera1", "Pumpkin Puree has great quality and arrived fresh."),
        (80, 4.0, "Cora2", "Solid value for a canned item; I would buy it again."),
        (80, 4.5, "Jonah3", "I like using Pumpkin Puree in my regular routine."),
        # Beverages
        (81, 4.5, "Wes1", "Sparkling Water has great quality and arrived fresh."),
        (81, 4.0, "Diego2", "Solid value for a beverages item; I would buy it again."),
        (81, 4.5, "Kira3", "I like using Sparkling Water in my regular routine."),
        (82, 4.5, "Xena1", "Cold Brew Coffee has great quality and arrived fresh."),
        (82, 4.0, "Emma2", "Solid value for a beverages item; I would buy it again."),
        (82, 4.5, "Leo3", "I like using Cold Brew Coffee in my regular routine."),
        (83, 4.5, "Yara1", "Kombucha has great quality and arrived fresh."),
        (83, 4.0, "Finn2", "Solid value for a beverages item; I would buy it again."),
        (83, 4.5, "Mila3", "I like using Kombucha in my regular routine."),
        (84, 4.5, "Zane1", "Aloe Vera Drink has great quality and arrived fresh."),
        (84, 4.0, "Gia2", "Solid value for a beverages item; I would buy it again."),
        (84, 4.5, "Noah3", "I like using Aloe Vera Drink in my regular routine."),
        (85, 4.5, "Ava1", "Coconut Water has great quality and arrived fresh."),
        (85, 4.0, "Hugo2", "Solid value for a beverages item; I would buy it again."),
        (85, 4.5, "Owen3", "I like using Coconut Water in my regular routine."),
        (86, 4.5, "Ben1", "Herbal Tonic has great quality and arrived fresh."),
        (86, 4.0, "Ivy2", "Solid value for a beverages item; I would buy it again."),
        (86, 4.5, "Pia3", "I like using Herbal Tonic in my regular routine."),
        (87, 4.5, "Cora1", "Oat Latte has great quality and arrived fresh."),
        (87, 4.0, "Jonah2", "Solid value for a beverages item; I would buy it again."),
        (87, 4.5, "Quinn3", "I like using Oat Latte in my regular routine."),
        (88, 4.5, "Diego1", "Green Juice has great quality and arrived fresh."),
        (88, 4.0, "Kira2", "Solid value for a beverages item; I would buy it again."),
        (88, 4.5, "Rosa3", "I like using Green Juice in my regular routine."),
        # Personal Care
        (89, 4.5, "Emma1", "Organic Shampoo has great quality and arrived fresh."),
        (89, 4.0, "Leo2", "Solid value for a personal-care item; I would buy it again."),
        (89, 4.5, "Sage3", "I like using Organic Shampoo in my regular routine."),
        (90, 4.5, "Finn1", "Toothpaste has great quality and arrived fresh."),
        (90, 4.0, "Mila2", "Solid value for a personal-care item; I would buy it again."),
        (90, 4.5, "Theo3", "I like using Toothpaste in my regular routine."),
        (91, 4.5, "Gia1", "Body Wash has great quality and arrived fresh."),
        (91, 4.0, "Noah2", "Solid value for a personal-care item; I would buy it again."),
        (91, 4.5, "Uma3", "I like using Body Wash in my regular routine."),
        (92, 4.5, "Hugo1", "Deodorant has great quality and arrived fresh."),
        (92, 4.0, "Owen2", "Solid value for a personal-care item; I would buy it again."),
        (92, 4.5, "Vera3", "I like using Deodorant in my regular routine."),
        (93, 4.5, "Ivy1", "Face Cleanser has great quality and arrived fresh."),
        (93, 4.0, "Pia2", "Solid value for a personal-care item; I would buy it again."),
        (93, 4.5, "Wes3", "I like using Face Cleanser in my regular routine."),
        (94, 4.5, "Jonah1", "Hand Soap has great quality and arrived fresh."),
        (94, 4.0, "Quinn2", "Solid value for a personal-care item; I would buy it again."),
        (94, 4.5, "Xena3", "I like using Hand Soap in my regular routine."),
        (95, 4.5, "Kira1", "Lip Balm has great quality and arrived fresh."),
        (95, 4.0, "Rosa2", "Solid value for a personal-care item; I would buy it again."),
        (95, 4.5, "Yara3", "I like using Lip Balm in my regular routine."),
        (96, 4.5, "Leo1", "Sunscreen has great quality and arrived fresh."),
        (96, 4.0, "Sage2", "Solid value for a personal-care item; I would buy it again."),
        (96, 4.5, "Zane3", "I like using Sunscreen in my regular routine."),
        # Household
        (97, 4.5, "Mila1", "Dish Soap has great quality and arrived fresh."),
        (97, 4.0, "Theo2", "Solid value for a household item; I would buy it again."),
        (97, 4.5, "Ava3", "I like using Dish Soap in my regular routine."),
        (98, 4.5, "Noah1", "Laundry Detergent has great quality and arrived fresh."),
        (98, 4.0, "Uma2", "Solid value for a household item; I would buy it again."),
        (98, 4.5, "Ben3", "I like using Laundry Detergent in my regular routine."),
        (99, 4.5, "Owen1", "Paper Towels has great quality and arrived fresh."),
        (99, 4.0, "Vera2", "Solid value for a household item; I would buy it again."),
        (99, 4.5, "Cora3", "I like using Paper Towels in my regular routine."),
        (100, 4.5, "Pia1", "Reusable Storage Bags has great quality and arrived fresh."),
        (100, 4.0, "Wes2", "Solid value for a household item; I would buy it again."),
        (100, 4.5, "Diego3", "I like using Reusable Storage Bags in my regular routine."),
    ]
    cursor.execute("DELETE FROM reviews")
    cursor.executemany(
        "INSERT INTO reviews (product_id, rating, reviewer_name, review_text) VALUES (?, ?, ?, ?)",
        reviews,
    )

    conn.commit()
    conn.close()
    print(f"Database created at: {DB_PATH}")


if __name__ == "__main__":
    create_database()
